In [1]:
from google.colab import drive
import os
drive.mount('/content/gdrive')
path = "/content/gdrive/MyDrive/project/fakeNews/ReINTEL"
os.chdir(path)

!pip install -r requirements.txt

import pandas as pd
import numpy as np

from preprocessing import *
from model import *

Mounted at /content/gdrive
     |████████████████████████████████| 1.7MB 4.9MB/s 
     |████████████████████████████████| 2.7MB 6.0MB/s 
     |████████████████████████████████| 1.8MB 7.8MB/s 
     |████████████████████████████████| 51kB 5.2MB/s 
     |████████████████████████████████| 133kB 9.7MB/s 
     |████████████████████████████████| 71kB 5.1MB/s 
     |████████████████████████████████| 2.9MB 9.6MB/s 
     |████████████████████████████████| 890kB 12.6MB/s 
     |████████████████████████████████| 112kB 12.5MB/s 
     |████████████████████████████████| 645kB 11.4MB/s 
  Created wheel for fastbpe: filename=fastBPE-0.1.0-cp36-cp36m-linux_x86_64.whl size=481488 sha256=e940ce693c5af967a82528d875bb7465de25671eb0eefd226f7aaff93287af6f
  Stored in directory: /root/.cache/pip/wheels/f3/0c/9c/fc62058b4d473a5602bcd3d3edfece796f123875379ea82d79
  Created wheel for vncorenlp: filename=vncorenlp-1.0.3-cp36-none-any.whl size=2645936 sha256=4af1bf7af54f9ba02fd36144987a8827490512146707e636ad00e7942

In [2]:
!nvidia-smi

Wed Jan 27 07:53:12 2021       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 460.32.03    Driver Version: 418.67       CUDA Version: 10.1     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla P100-PCIE...  Off  | 00000000:00:04.0 Off |                    0 |
| N/A   43C    P0    28W / 250W |     10MiB / 16280MiB |      0%      Default |
|                               |                      |                 ERR! |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

#1. LOAD DATA AND OVERVIEW

In [ ]:
data_balance = pd.read_csv('data_balance.csv', encoding='utf-8')
test = pd.read_csv('test.csv', encoding='utf-8')

data_balance.head(3)

id  ...                           post_message_notStopword
0   502  ...  ghen cô vy là dự_án sáng_tạo của viện sức_khoẻ...
1  1613  ...  hnay hội_đồng thẩm_phán sẽ ra phán_quyết đối_v...
2   913  ...  emoji đêm cdc hà_nội thông_báo kết_quả trường_...

[3 rows x 11 columns]

In [ ]:
test.head(3)

id  ...                           post_message_notStopword
0   6  ...  trong giờ học thể dụ c do thầy_giáo nguyễn_văn...
1   7  ...  chủ đầu_tư tại hà_nội tung sản_phẩm có mức giá...
2  12  ...  thông_điệp của bức tranh mang tên là khải_hoàn...

[3 rows x 11 columns]

#2. BUILD MODEL

##2.1. Build model with post_message (original) with bpe



In [ ]:
train_sents = data_balance.post_message.values
train_labels = data_balance.label.values

test_text = test.post_message.values
test_labels = test.label.values

path="./models/Bert_original_bpe.pt"

BERT, vectorizer = bert_train(train_sents, train_labels, test_text, test_labels, device = 'cuda', epochs = 10, path=path, w2v='bpe')

# predict for test set 
test_labels_pred = bert_predict(test_text, BERT, vectorizer, w2v='bpe')
print('*'*100)
report(test_labels_pred, test_labels, name='Test')

Some weights of the model checkpoint at PhoBERT_base_transformers/model.bin were not used when initializing RobertaForSequenceClassification: ['lm_head.bias', 'lm_head.dense.weight', 'lm_head.dense.bias', 'lm_head.layer_norm.weight', 'lm_head.layer_norm.bias', 'lm_head.decoder.weight', 'lm_head.decoder.bias', 'roberta.pooler.dense.weight', 'roberta.pooler.dense.bias']
- This IS expected if you are initializing RobertaForSequenceClassification from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing RobertaForSequenceClassification from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Some weights of RobertaForSequenceClassification were not initialized from the model checkpoint at PhoBERT_base_transformers/model

Done
======== Epoch 1 / 10 ========
Training...



 Accuracy: 0.7174
 F1 score: 0.6854
 Average training loss: 0.5371
Running Validation...



 Accuracy: 0.8793
 F1 score: 0.8719
======== Epoch 2 / 10 ========
Training...



 Accuracy: 0.8646
 F1 score: 0.8569
 Average training loss: 0.3366
Running Validation...



 Accuracy: 0.7485
 F1 score: 0.7150
======== Epoch 3 / 10 ========
Training...



 Accuracy: 0.8854
 F1 score: 0.8793
 Average training loss: 0.2815
Running Validation...



 Accuracy: 0.8856
 F1 score: 0.8758
======== Epoch 4 / 10 ========
Training...



 Accuracy: 0.8958
 F1 score: 0.8919
 Average training loss: 0.2696
Running Validation...



 Accuracy: 0.8918
 F1 score: 0.8848
======== Epoch 5 / 10 ========
Training...



 Accuracy: 0.9500
 F1 score: 0.9485
 Average training loss: 0.1502
Running Validation...



 Accuracy: 0.8793
 F1 score: 0.8696
======== Epoch 6 / 10 ========
Training...



 Accuracy: 0.9792
 F1 score: 0.9786
 Average training loss: 0.0692
Running Validation...



 Accuracy: 0.8461
 F1 score: 0.8345
======== Epoch 7 / 10 ========
Training...



 Accuracy: 0.9743
 F1 score: 0.9737
 Average training loss: 0.0771
Running Validation...



 Accuracy: 0.8080
 F1 score: 0.7898
======== Epoch 8 / 10 ========
Training...



 Accuracy: 0.9729
 F1 score: 0.9721
 Average training loss: 0.1016
Running Validation...



 Accuracy: 0.8918
 F1 score: 0.8830
======== Epoch 9 / 10 ========
Training...



 Accuracy: 0.9910
 F1 score: 0.9907
 Average training loss: 0.0289
Running Validation...



 Accuracy: 0.8537
 F1 score: 0.8393
======== Epoch 10 / 10 ========
Training...



 Accuracy: 0.9833
 F1 score: 0.9827
 Average training loss: 0.0617
Running Validation...



 Accuracy: 0.8856
 F1 score: 0.8778
Training complete!

Report for Train set:
              precision    recall  f1-score   support

           0       0.99      1.00      1.00       734
           1       1.00      0.99      1.00       675

    accuracy                           1.00      1409
   macro avg       1.00      1.00      1.00      1409
weighted avg       1.00      1.00      1.00      1409


Confusion maxtrix:
[[734   0]
 [  4 671]]
****************************************************************************************************
Report for validation set:
              precision    recall  f1-score   support

           0       0.89      0.91      0.90        86
           1       0.88      0.86      0.87        71

    accuracy                           0.89       157
   macro avg       0.89      0.88      0.88       157
weighted avg       0.89      0.89      0.89       157


Confusion maxtrix:
[[78  8]
 [10 61]]
Save model:  ./models/Bert_original_bpe.pt
**************

##2.2. Build model with post_message_notStopword with bpe

In [ ]:
train_sents = data_balance.post_message_notStopword.values
train_labels = data_balance.label.values

test_text = test.post_message_notStopword.values
test_labels = test.label.values

path="./models/Bert_notStopword_bpe.pt"

BERT, vectorizer = bert_train(train_sents, train_labels, test_text, test_labels, device = 'cuda', epochs = 10, path=path, w2v='bpe')

# predict for test set 
test_labels_pred = bert_predict(test_text, BERT, vectorizer, w2v='bpe')
print('*'*100)
report(test_labels_pred, test_labels, name='Test')

Some weights of the model checkpoint at PhoBERT_base_transformers/model.bin were not used when initializing RobertaForSequenceClassification: ['lm_head.bias', 'lm_head.dense.weight', 'lm_head.dense.bias', 'lm_head.layer_norm.weight', 'lm_head.layer_norm.bias', 'lm_head.decoder.weight', 'lm_head.decoder.bias', 'roberta.pooler.dense.weight', 'roberta.pooler.dense.bias']
- This IS expected if you are initializing RobertaForSequenceClassification from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing RobertaForSequenceClassification from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Some weights of RobertaForSequenceClassification were not initialized from the model checkpoint at PhoBERT_base_transformers/model

Done
======== Epoch 1 / 10 ========
Training...



 Accuracy: 0.7271
 F1 score: 0.7012
 Average training loss: 0.5310
Running Validation...



 Accuracy: 0.7754
 F1 score: 0.7472
======== Epoch 2 / 10 ========
Training...



 Accuracy: 0.8889
 F1 score: 0.8846
 Average training loss: 0.2820
Running Validation...



 Accuracy: 0.7836
 F1 score: 0.7536
======== Epoch 3 / 10 ========
Training...



 Accuracy: 0.9389
 F1 score: 0.9361
 Average training loss: 0.1691
Running Validation...



 Accuracy: 0.8080
 F1 score: 0.7877
======== Epoch 4 / 10 ========
Training...



 Accuracy: 0.9299
 F1 score: 0.9272
 Average training loss: 0.2114
Running Validation...



 Accuracy: 0.9187
 F1 score: 0.9133
======== Epoch 5 / 10 ========
Training...



 Accuracy: 0.9493
 F1 score: 0.9475
 Average training loss: 0.1482
Running Validation...



 Accuracy: 0.9431
 F1 score: 0.9388
======== Epoch 6 / 10 ========
Training...



 Accuracy: 0.9875
 F1 score: 0.9870
 Average training loss: 0.0462
Running Validation...



 Accuracy: 0.8981
 F1 score: 0.8905
======== Epoch 7 / 10 ========
Training...



 Accuracy: 0.9924
 F1 score: 0.9920
 Average training loss: 0.0298
Running Validation...



 Accuracy: 0.8224
 F1 score: 0.8022
======== Epoch 8 / 10 ========
Training...



 Accuracy: 0.9910
 F1 score: 0.9906
 Average training loss: 0.0325
Running Validation...



 Accuracy: 0.8343
 F1 score: 0.8188
======== Epoch 9 / 10 ========
Training...



 Accuracy: 0.9764
 F1 score: 0.9757
 Average training loss: 0.0908
Running Validation...



 Accuracy: 0.7955
 F1 score: 0.7745
======== Epoch 10 / 10 ========
Training...



 Accuracy: 0.9715
 F1 score: 0.9705
 Average training loss: 0.0931
Running Validation...



 Accuracy: 0.9425
 F1 score: 0.9388
Training complete!

Report for Train set:
              precision    recall  f1-score   support

           0       0.99      1.00      1.00       734
           1       1.00      0.99      1.00       675

    accuracy                           1.00      1409
   macro avg       1.00      1.00      1.00      1409
weighted avg       1.00      1.00      1.00      1409


Confusion maxtrix:
[[734   0]
 [  4 671]]
****************************************************************************************************
Report for validation set:
              precision    recall  f1-score   support

           0       0.93      0.97      0.95        86
           1       0.96      0.92      0.94        71

    accuracy                           0.94       157
   macro avg       0.94      0.94      0.94       157
weighted avg       0.94      0.94      0.94       157


Confusion maxtrix:
[[83  3]
 [ 6 65]]
Save model:  ./models/Bert_notStopword_bpe.pt
***********

## 2.3 Build model with post_message_preproced with bpe

In [ ]:
train_sents = data_balance.post_message_preproced.values
train_labels = data_balance.label.values

test_text = test.post_message_preproced.values
test_labels = test.label.values

path="./models/Bert_preproced_bpe.pt"

BERT, vectorizer = bert_train(train_sents, train_labels, test_text, test_labels, device = 'cuda', epochs = 10, path=path, w2v='bpe')

# predict for test set 
test_labels_pred = bert_predict(test_text, BERT, vectorizer, w2v='bpe')
print('*'*100)
report(test_labels_pred, test_labels, name='Test')

Some weights of the model checkpoint at PhoBERT_base_transformers/model.bin were not used when initializing RobertaForSequenceClassification: ['lm_head.bias', 'lm_head.dense.weight', 'lm_head.dense.bias', 'lm_head.layer_norm.weight', 'lm_head.layer_norm.bias', 'lm_head.decoder.weight', 'lm_head.decoder.bias', 'roberta.pooler.dense.weight', 'roberta.pooler.dense.bias']
- This IS expected if you are initializing RobertaForSequenceClassification from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing RobertaForSequenceClassification from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Some weights of RobertaForSequenceClassification were not initialized from the model checkpoint at PhoBERT_base_transformers/model

Done
======== Epoch 1 / 10 ========
Training...



 Accuracy: 0.6431
 F1 score: 0.6013
 Average training loss: 0.6120
Running Validation...



 Accuracy: 0.7942
 F1 score: 0.7763
======== Epoch 2 / 10 ========
Training...



 Accuracy: 0.8368
 F1 score: 0.8281
 Average training loss: 0.3902
Running Validation...



 Accuracy: 0.8323
 F1 score: 0.8232
======== Epoch 3 / 10 ========
Training...



 Accuracy: 0.8924
 F1 score: 0.8887
 Average training loss: 0.2673
Running Validation...



 Accuracy: 0.8073
 F1 score: 0.7916
======== Epoch 4 / 10 ========
Training...



 Accuracy: 0.9083
 F1 score: 0.9045
 Average training loss: 0.2302
Running Validation...



 Accuracy: 0.8849
 F1 score: 0.8807
======== Epoch 5 / 10 ========
Training...



 Accuracy: 0.9368
 F1 score: 0.9348
 Average training loss: 0.1686
Running Validation...



 Accuracy: 0.8918
 F1 score: 0.8884
======== Epoch 6 / 10 ========
Training...



 Accuracy: 0.9750
 F1 score: 0.9739
 Average training loss: 0.0817
Running Validation...



 Accuracy: 0.8599
 F1 score: 0.8478
======== Epoch 7 / 10 ========
Training...



 Accuracy: 0.9722
 F1 score: 0.9712
 Average training loss: 0.0800
Running Validation...



 Accuracy: 0.8599
 F1 score: 0.8502
======== Epoch 8 / 10 ========
Training...



 Accuracy: 0.9826
 F1 score: 0.9819
 Average training loss: 0.0556
Running Validation...



 Accuracy: 0.8136
 F1 score: 0.7947
======== Epoch 9 / 10 ========
Training...



 Accuracy: 0.9722
 F1 score: 0.9715
 Average training loss: 0.1025
Running Validation...



 Accuracy: 0.8593
 F1 score: 0.8503
======== Epoch 10 / 10 ========
Training...



 Accuracy: 0.9819
 F1 score: 0.9812
 Average training loss: 0.0709
Running Validation...



 Accuracy: 0.8849
 F1 score: 0.8800
Training complete!

Report for Train set:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00       734
           1       1.00      1.00      1.00       675

    accuracy                           1.00      1409
   macro avg       1.00      1.00      1.00      1409
weighted avg       1.00      1.00      1.00      1409


Confusion maxtrix:
[[732   2]
 [  1 674]]
****************************************************************************************************
Report for validation set:
              precision    recall  f1-score   support

           0       0.90      0.90      0.90        86
           1       0.87      0.87      0.87        71

    accuracy                           0.89       157
   macro avg       0.88      0.88      0.88       157
weighted avg       0.89      0.89      0.89       157


Confusion maxtrix:
[[77  9]
 [ 9 62]]
Save model:  ./models/Bert_preproced_bpe.pt
*************

## 2.4. Build model with post_message (original) with bpe_tfidf

In [ ]:
train_sents = data_balance.post_message.values
train_labels = data_balance.label.values

test_text = test.post_message.values
test_labels = test.label.values

path="./models/Bert_original_bpe_tfidf.pt"

BERT, vectorizer = bert_train(train_sents, train_labels, test_text, test_labels, device = 'cuda', epochs = 10, path=path, w2v='bpe_tfidf')

# predict for test set 
test_labels_pred = bert_predict(test_text, BERT, vectorizer, w2v='bpe_tfidf')
print('*'*100)
report(test_labels_pred, test_labels, name='Test')

Some weights of the model checkpoint at PhoBERT_base_transformers/model.bin were not used when initializing RobertaForSequenceClassification: ['lm_head.bias', 'lm_head.dense.weight', 'lm_head.dense.bias', 'lm_head.layer_norm.weight', 'lm_head.layer_norm.bias', 'lm_head.decoder.weight', 'lm_head.decoder.bias', 'roberta.pooler.dense.weight', 'roberta.pooler.dense.bias']
- This IS expected if you are initializing RobertaForSequenceClassification from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing RobertaForSequenceClassification from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Some weights of RobertaForSequenceClassification were not initialized from the model checkpoint at PhoBERT_base_transformers/model

Done
======== Epoch 1 / 10 ========
Training...



 Accuracy: 0.6653
 F1 score: 0.6108
 Average training loss: 0.6009
Running Validation...



 Accuracy: 0.7429
 F1 score: 0.7201
======== Epoch 2 / 10 ========
Training...



 Accuracy: 0.8556
 F1 score: 0.8487
 Average training loss: 0.3566
Running Validation...



 Accuracy: 0.8067
 F1 score: 0.7928
======== Epoch 3 / 10 ========
Training...



 Accuracy: 0.9215
 F1 score: 0.9187
 Average training loss: 0.2264
Running Validation...



 Accuracy: 0.8461
 F1 score: 0.8363
======== Epoch 4 / 10 ========
Training...



 Accuracy: 0.9368
 F1 score: 0.9344
 Average training loss: 0.1774
Running Validation...



 Accuracy: 0.8586
 F1 score: 0.8505
======== Epoch 5 / 10 ========
Training...



 Accuracy: 0.9271
 F1 score: 0.9250
 Average training loss: 0.2024
Running Validation...



 Accuracy: 0.8655
 F1 score: 0.8596
======== Epoch 6 / 10 ========
Training...



 Accuracy: 0.9771
 F1 score: 0.9761
 Average training loss: 0.0757
Running Validation...



 Accuracy: 0.8718
 F1 score: 0.8633
======== Epoch 7 / 10 ========
Training...



 Accuracy: 0.9861
 F1 score: 0.9856
 Average training loss: 0.0554
Running Validation...



 Accuracy: 0.8524
 F1 score: 0.8442
======== Epoch 8 / 10 ========
Training...



 Accuracy: 0.9889
 F1 score: 0.9885
 Average training loss: 0.0391
Running Validation...



 Accuracy: 0.8392
 F1 score: 0.8254
======== Epoch 9 / 10 ========
Training...



 Accuracy: 0.9847
 F1 score: 0.9842
 Average training loss: 0.0469
Running Validation...



 Accuracy: 0.8586
 F1 score: 0.8478
======== Epoch 10 / 10 ========
Training...



 Accuracy: 0.9938
 F1 score: 0.9935
 Average training loss: 0.0266
Running Validation...



 Accuracy: 0.8524
 F1 score: 0.8420
Training complete!

Report for Train set:
              precision    recall  f1-score   support

           0       0.99      1.00      1.00       734
           1       1.00      0.99      1.00       675

    accuracy                           1.00      1409
   macro avg       1.00      1.00      1.00      1409
weighted avg       1.00      1.00      1.00      1409


Confusion maxtrix:
[[734   0]
 [  6 669]]
****************************************************************************************************
Report for validation set:
              precision    recall  f1-score   support

           0       0.84      0.91      0.87        86
           1       0.88      0.79      0.83        71

    accuracy                           0.85       157
   macro avg       0.86      0.85      0.85       157
weighted avg       0.86      0.85      0.85       157


Confusion maxtrix:
[[78  8]
 [15 56]]
Save model:  ./models/Bert_original_bpe_tfidf.pt
********

##2.5. Build model with post_message_notStopword with bpe_tfidf

In [ ]:
train_sents = data_balance.post_message_notStopword.values
train_labels = data_balance.label.values

test_text = test.post_message_notStopword.values
test_labels = test.label.values

path="./models/Bert_notStopword_bpe_tfidf.pt"

BERT, vectorizer = bert_train(train_sents, train_labels, test_text, test_labels, device = 'cuda', epochs = 10, path=path, w2v='bpe_tfidf')

# predict for test set 
test_labels_pred = bert_predict(test_text, BERT, vectorizer, w2v='bpe_tfidf')
print('*'*100)
report(test_labels_pred, test_labels, name='Test')

Some weights of the model checkpoint at PhoBERT_base_transformers/model.bin were not used when initializing RobertaForSequenceClassification: ['lm_head.bias', 'lm_head.dense.weight', 'lm_head.dense.bias', 'lm_head.layer_norm.weight', 'lm_head.layer_norm.bias', 'lm_head.decoder.weight', 'lm_head.decoder.bias', 'roberta.pooler.dense.weight', 'roberta.pooler.dense.bias']
- This IS expected if you are initializing RobertaForSequenceClassification from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing RobertaForSequenceClassification from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Some weights of RobertaForSequenceClassification were not initialized from the model checkpoint at PhoBERT_base_transformers/model

Done
======== Epoch 1 / 10 ========
Training...



 Accuracy: 0.6389
 F1 score: 0.5723
 Average training loss: 0.6152
Running Validation...



 Accuracy: 0.6722
 F1 score: 0.6019
======== Epoch 2 / 10 ========
Training...



 Accuracy: 0.8514
 F1 score: 0.8460
 Average training loss: 0.3596
Running Validation...



 Accuracy: 0.7623
 F1 score: 0.7341
======== Epoch 3 / 10 ========
Training...



 Accuracy: 0.9042
 F1 score: 0.8994
 Average training loss: 0.2498
Running Validation...



 Accuracy: 0.8205
 F1 score: 0.8050
======== Epoch 4 / 10 ========
Training...



 Accuracy: 0.8938
 F1 score: 0.8869
 Average training loss: 0.2640
Running Validation...



 Accuracy: 0.9050
 F1 score: 0.8972
======== Epoch 5 / 10 ========
Training...



 Accuracy: 0.9535
 F1 score: 0.9522
 Average training loss: 0.1418
Running Validation...



 Accuracy: 0.8724
 F1 score: 0.8619
======== Epoch 6 / 10 ========
Training...



 Accuracy: 0.9833
 F1 score: 0.9823
 Average training loss: 0.0565
Running Validation...



 Accuracy: 0.8662
 F1 score: 0.8537
======== Epoch 7 / 10 ========
Training...



 Accuracy: 0.9875
 F1 score: 0.9871
 Average training loss: 0.0477
Running Validation...



 Accuracy: 0.8129
 F1 score: 0.7962
======== Epoch 8 / 10 ========
Training...



 Accuracy: 0.9917
 F1 score: 0.9913
 Average training loss: 0.0301
Running Validation...



 Accuracy: 0.8198
 F1 score: 0.8030
======== Epoch 9 / 10 ========
Training...



 Accuracy: 0.9604
 F1 score: 0.9594
 Average training loss: 0.1523
Running Validation...



 Accuracy: 0.8849
 F1 score: 0.8769
======== Epoch 10 / 10 ========
Training...



 Accuracy: 0.9868
 F1 score: 0.9864
 Average training loss: 0.0466
Running Validation...



 Accuracy: 0.8981
 F1 score: 0.8921
Training complete!

Report for Train set:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00       734
           1       1.00      1.00      1.00       675

    accuracy                           1.00      1409
   macro avg       1.00      1.00      1.00      1409
weighted avg       1.00      1.00      1.00      1409


Confusion maxtrix:
[[734   0]
 [  2 673]]
****************************************************************************************************
Report for validation set:
              precision    recall  f1-score   support

           0       0.92      0.90      0.91        86
           1       0.88      0.90      0.89        71

    accuracy                           0.90       157
   macro avg       0.90      0.90      0.90       157
weighted avg       0.90      0.90      0.90       157


Confusion maxtrix:
[[77  9]
 [ 7 64]]
Save model:  ./models/Bert_notStopword_bpe_tfidf.pt
*****

## 2.6 Build model with post_message_preproced with bpe_tfidf

In [ ]:
train_sents = data_balance.post_message_preproced.values
train_labels = data_balance.label.values

test_text = test.post_message_preproced.values
test_labels = test.label.values

path="./models/Bert_preproced_bpe_tfidf.pt"

BERT, vectorizer = bert_train(train_sents, train_labels, test_text, test_labels, device = 'cuda', epochs = 10, path=path, w2v='bpe_tfidf')

# predict for test set 
test_labels_pred = bert_predict(test_text, BERT, vectorizer, w2v='bpe_tfidf')
print('*'*100)
report(test_labels_pred, test_labels, name='Test')

Some weights of the model checkpoint at PhoBERT_base_transformers/model.bin were not used when initializing RobertaForSequenceClassification: ['lm_head.bias', 'lm_head.dense.weight', 'lm_head.dense.bias', 'lm_head.layer_norm.weight', 'lm_head.layer_norm.bias', 'lm_head.decoder.weight', 'lm_head.decoder.bias', 'roberta.pooler.dense.weight', 'roberta.pooler.dense.bias']
- This IS expected if you are initializing RobertaForSequenceClassification from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing RobertaForSequenceClassification from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Some weights of RobertaForSequenceClassification were not initialized from the model checkpoint at PhoBERT_base_transformers/model

Done
======== Epoch 1 / 10 ========
Training...



 Accuracy: 0.6569
 F1 score: 0.6033
 Average training loss: 0.6281
Running Validation...



 Accuracy: 0.7679
 F1 score: 0.7464
======== Epoch 2 / 10 ========
Training...



 Accuracy: 0.8056
 F1 score: 0.7965
 Average training loss: 0.4320
Running Validation...



 Accuracy: 0.7429
 F1 score: 0.7036
======== Epoch 3 / 10 ========
Training...



 Accuracy: 0.8681
 F1 score: 0.8621
 Average training loss: 0.3264
Running Validation...



 Accuracy: 0.7297
 F1 score: 0.6872
======== Epoch 4 / 10 ========
Training...



 Accuracy: 0.8938
 F1 score: 0.8886
 Average training loss: 0.2748
Running Validation...



 Accuracy: 0.8636
 F1 score: 0.8569
======== Epoch 5 / 10 ========
Training...



 Accuracy: 0.9132
 F1 score: 0.9100
 Average training loss: 0.2232
Running Validation...



 Accuracy: 0.8774
 F1 score: 0.8696
======== Epoch 6 / 10 ========
Training...



 Accuracy: 0.9632
 F1 score: 0.9621
 Average training loss: 0.1129
Running Validation...



 Accuracy: 0.8504
 F1 score: 0.8427
======== Epoch 7 / 10 ========
Training...



 Accuracy: 0.9674
 F1 score: 0.9664
 Average training loss: 0.0947
Running Validation...



 Accuracy: 0.8718
 F1 score: 0.8643
======== Epoch 8 / 10 ========
Training...



 Accuracy: 0.9868
 F1 score: 0.9863
 Average training loss: 0.0464
Running Validation...



 Accuracy: 0.8774
 F1 score: 0.8699
======== Epoch 9 / 10 ========
Training...



 Accuracy: 0.9861
 F1 score: 0.9854
 Average training loss: 0.0543
Running Validation...



 Accuracy: 0.8774
 F1 score: 0.8696
======== Epoch 10 / 10 ========
Training...



 Accuracy: 0.9882
 F1 score: 0.9877
 Average training loss: 0.0436
Running Validation...



 Accuracy: 0.8843
 F1 score: 0.8766
Training complete!

Report for Train set:
              precision    recall  f1-score   support

           0       0.99      1.00      0.99       734
           1       1.00      0.99      0.99       675

    accuracy                           0.99      1409
   macro avg       0.99      0.99      0.99      1409
weighted avg       0.99      0.99      0.99      1409


Confusion maxtrix:
[[732   2]
 [  9 666]]
****************************************************************************************************
Report for validation set:
              precision    recall  f1-score   support

           0       0.85      0.95      0.90        86
           1       0.93      0.80      0.86        71

    accuracy                           0.89       157
   macro avg       0.89      0.88      0.88       157
weighted avg       0.89      0.89      0.88       157


Confusion maxtrix:
[[82  4]
 [14 57]]
Save model:  ./models/Bert_preproced_bpe_tfidf.pt
*******

#3. OVER SAMPLING

In [ ]:
# import libraries
# check version number of sampling library
import imblearn
print(imblearn.__version__)

from collections import Counter
from imblearn.over_sampling import RandomOverSampler
import pandas as pd
import numpy as np

# take data
data = pd.read_csv('train.csv', encoding='utf-8')
test = pd.read_csv('test.csv', encoding='utf-8')

train_sents = data.post_message.values
train_labels = data.label.values

test_text = test.post_message_preproced.values
test_labels = test.label.values

# define oversampling startegy 
oversample = RandomOverSampler(sampling_strategy=0.3)

# fit and apply the transform
train_sents_over, train_labels_over = oversample.fit_resample(train_sents.reshape(-1,1), train_labels.reshape(-1,1))
train_sents_over, train_labels_over = train_sents_over.reshape(-1), train_labels_over.reshape(-1)
# summarize class distribution
print(Counter(train_labels_over))

0.4.3
Counter({0: 3334, 1: 1000})


/usr/local/lib/python3.6/dist-packages/sklearn/utils/validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.6/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function safe_indexing is deprecated; safe_indexing is deprecated in version 0.22 and will be removed in version 0.24.
  warnings.warn(msg, category=FutureWarning)


In [ ]:
# Train model with Bert_original_bpe_tfidf_overSampling
path="./models/Bert_original_bpe_tfidf_overSampling.pt"

BERT, vectorizer = bert_train(train_sents_over, train_labels_over, test_text, test_labels, device = 'cuda', epochs = 10, path=path, w2v='bpe_tfidf')

# predict for test set 
test_labels_pred = bert_predict(test_text, BERT, vectorizer, w2v='bpe_tfidf')
print('*'*100)
report(test_labels_pred, test_labels, name='Test')

Some weights of the model checkpoint at PhoBERT_base_transformers/model.bin were not used when initializing RobertaForSequenceClassification: ['lm_head.bias', 'lm_head.dense.weight', 'lm_head.dense.bias', 'lm_head.layer_norm.weight', 'lm_head.layer_norm.bias', 'lm_head.decoder.weight', 'lm_head.decoder.bias', 'roberta.pooler.dense.weight', 'roberta.pooler.dense.bias']
- This IS expected if you are initializing RobertaForSequenceClassification from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing RobertaForSequenceClassification from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Some weights of RobertaForSequenceClassification were not initialized from the model checkpoint at PhoBERT_base_transformers/model

Done
======== Epoch 1 / 10 ========
Training...



 Accuracy: 0.8181
 F1 score: 0.6672
 Average training loss: 0.4102
Running Validation...



 Accuracy: 0.9045
 F1 score: 0.8294
======== Epoch 2 / 10 ========
Training...



 Accuracy: 0.9121
 F1 score: 0.8633
 Average training loss: 0.2331
Running Validation...



 Accuracy: 0.9224
 F1 score: 0.8604
======== Epoch 3 / 10 ========
Training...



 Accuracy: 0.9511
 F1 score: 0.9262
 Average training loss: 0.1477
Running Validation...



 Accuracy: 0.9420
 F1 score: 0.9072
======== Epoch 4 / 10 ========
Training...



 Accuracy: 0.9670
 F1 score: 0.9481
 Average training loss: 0.1151
Running Validation...



 Accuracy: 0.9425
 F1 score: 0.9017
======== Epoch 5 / 10 ========
Training...



 Accuracy: 0.9823
 F1 score: 0.9731
 Average training loss: 0.0645
Running Validation...



 Accuracy: 0.9402
 F1 score: 0.8920
======== Epoch 6 / 10 ========
Training...



 Accuracy: 0.9900
 F1 score: 0.9840
 Average training loss: 0.0465
Running Validation...



 Accuracy: 0.9621
 F1 score: 0.9333
======== Epoch 7 / 10 ========
Training...



 Accuracy: 0.9939
 F1 score: 0.9911
 Average training loss: 0.0288
Running Validation...



 Accuracy: 0.9598
 F1 score: 0.9303
======== Epoch 8 / 10 ========
Training...



 Accuracy: 0.9936
 F1 score: 0.9901
 Average training loss: 0.0259
Running Validation...



 Accuracy: 0.9643
 F1 score: 0.9365
======== Epoch 9 / 10 ========
Training...



 Accuracy: 0.9946
 F1 score: 0.9913
 Average training loss: 0.0203
Running Validation...



 Accuracy: 0.9425
 F1 score: 0.8938
======== Epoch 10 / 10 ========
Training...



 Accuracy: 0.9962
 F1 score: 0.9941
 Average training loss: 0.0160
Running Validation...



 Accuracy: 0.9559
 F1 score: 0.9200
Training complete!

Report for Train set:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00      2986
           1       1.00      0.99      1.00       914

    accuracy                           1.00      3900
   macro avg       1.00      1.00      1.00      3900
weighted avg       1.00      1.00      1.00      3900


Confusion maxtrix:
[[2985    1]
 [   7  907]]
****************************************************************************************************
Report for validation set:
              precision    recall  f1-score   support

           0       0.96      0.99      0.97       348
           1       0.94      0.84      0.88        86

    accuracy                           0.96       434
   macro avg       0.95      0.91      0.93       434
weighted avg       0.96      0.96      0.96       434


Confusion maxtrix:
[[343   5]
 [ 14  72]]
Save model:  ./models/Bert_original_bpe_tfidf_ove

# LOAD MODELS

In [ ]:
path="./models/Bert_original.pt"
model = torch.load(path)
model.eval()

RobertaForSequenceClassification(
  (roberta): RobertaModel(
    (embeddings): RobertaEmbeddings(
      (word_embeddings): Embedding(64001, 768, padding_idx=0)
      (position_embeddings): Embedding(258, 768, padding_idx=0)
      (token_type_embeddings): Embedding(1, 768)
      (LayerNorm): LayerNorm((768,), eps=1e-05, elementwise_affine=True)
      (dropout): Dropout(p=0.1, inplace=False)
    )
    (encoder): RobertaEncoder(
      (layer): ModuleList(
        (0): RobertaLayer(
          (attention): RobertaAttention(
            (self): RobertaSelfAttention(
              (query): Linear(in_features=768, out_features=768, bias=True)
              (key): Linear(in_features=768, out_features=768, bias=True)
              (value): Linear(in_features=768, out_features=768, bias=True)
              (dropout): Dropout(p=0.1, inplace=False)
            )
            (output): RobertaSelfOutput(
              (dense): Linear(in_features=768, out_features=768, bias=True)
              (LayerN